
#spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    initialization-mode: always
#    username: sa
#    password: ''
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: none

      
# Oracle settings
#Spring web environment as false
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: mmoney
    password: mmoney
    url: jdbc:oracle:thin:@localhost:20303:PRTP
    #hikari: 
     # connection-test-query:  SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
  main:
    web-application-type: servlet
  mvc:
    async:
      request-timeout: 3600000